# Generated by Django 5.1.1 on 2024-09-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_profile_management', '0002_vendor_is_active_vendor_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
