# Generated by Django 5.1.1 on 2024-09-06 17:10

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vendor_profile_management', '0003_vendor_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='vendor_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='vendor_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='username',
            field=models.CharField(default=1, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
