# Generated by Django 5.1.1 on 2024-09-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_profile_management', '0005_historicalperformance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperformance',
            name='date',
        ),
    ]
