# Generated by Django 5.1.1 on 2024-09-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_profile_management', '0006_remove_historicalperformance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
